webaccountbookapi/urls.py
from django.urls import path,re_path

from . import views

app_name = "webaccountbookapi"

urlpatterns = [
    path('create/',views.SignUp.as_view(),name='create'),
    path('login/',views.login_to_index.as_view(),name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('',views.index,name='index'),
    path('add_purchase/',views.add_purchase,name="add_purchase"),
    path('<int:purchase_id>/delete',views.delete_purchase,name="delete_purchase"),
    path('genre/add/',views.add_genre,name="add_genre"),
    path('update_budget/',views.update_budget,name="update_budget"),
    path('genre/<int:genre_id>/delete/',views.delete_genre,name="delete_genre"),
]

webaccountbookbackend/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings #画像参照のため追加
from django.contrib.staticfiles.urls import static #画像参照のため追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account_book/',include('webaccountbookapi.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webaccountbookapi/models.py
from django.db import models
from django.core.files import File
import datetime
import os
from .storage import OverwriteStorage
from django.contrib.auth.models import User,AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils import timezone

# Create your models here.
class UserBindQuerySet(models.QuerySet):
    def bind_user(self,user):
        return self.filter(author=user)

    def thismonth(self):
        now = timezone.now()
        return self.filter(purchase_date__year=now.year).filter(purchase_date__month=now.month).order_by('purchase_date')


class Genre(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    genre_name = models.CharField(max_length=100)
    objects = UserBindQuerySet.as_manager()

    def __str__(self):
        return self.genre_name

class Purchase(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    price = models.IntegerField(default=0)
    purchase_date = models.DateField(auto_now=False,default=datetime.date.today)

    objects = UserBindQuerySet.as_manager()

    def __str__(self):
        return self.name

class NameOnlyUserManager(BaseUserManager):
    def create_user(self,username,password=None):
        if not username:
            raise ValueError('Users must have a username')
        user = self.model(username)
        user.save(using=self._db)
        return user

class NameOnlyUser(AbstractBaseUser):
    username = models.CharField(max_length=20,unique=True)
    USERNAME_FIELD = 'username'
    objects = NameOnlyUserManager()



class Siteuser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="siteuser")
    monthly_budget = models.IntegerField(default=50000)

    @receiver(post_save,sender=settings.AUTH_USER_MODEL)
    def create_site_user(sender,instance,created,**kwargs):
        if created:
            Siteuser.objects.create(user=instance)

    @receiver(post_save,sender=settings.AUTH_USER_MODEL)
    def save_site_user(sender,instance,**kwargs):
        instance.siteuser.save()

class Graphs(models.Model):
    graph = models.ImageField(upload_to='images/',blank=True,storage=OverwriteStorage())

webaccountbookapi/forms.py
from django import forms
from django.utils import timezone

from .models import Purchase,Genre,Siteuser,NameOnlyUser
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model,authenticate
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.forms import UsernameField
from django.utils.text import capfirst


UserModel = get_user_model()

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['name','genre','price','purchase_date']
        labels = {
            'name':'名前',
            'genre':'ジャンル',
            'price':'価格',
            'purchase_date':'購入日',
        }
        widgets = {
            'purchase_date': forms.SelectDateWidget(years=[x for x in range(timezone.now().year - 1,timezone.now().year + 1)]),
        }
        label_suffix = ''

class SiteuserForm(forms.ModelForm):
    class Meta:
        model = Siteuser
        fields = ['monthly_budget']
        labels = {
        'monthly_budget':'今月の予算',
        }


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['genre_name',]
        labels = {
            'genre_name':"ジャンル名"
        }



class AuthenticationFormWithoutPassword(forms.Form):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True}))


    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args,label_suffix="",**kwargs)

        # Set the max length and label for the "username" field.
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        username_max_length = self.username_field.max_length or 254
        self.fields['username'].max_length = username_max_length
        self.fields['username'].widget.attrs['maxlength'] = username_max_length
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')

        if username is not None:
            self.user_cache = authenticate(self.request, username=username)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'username': self.username_field.verbose_name},
        )

class SignUpForm(forms.ModelForm):
    class Meta:
        model = NameOnlyUser
        fields = ['username']

webaccountbookapi/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.shortcuts import render,get_object_or_404
from django.views.generic.edit import CreateView
from django.utils import timezone

from .forms import PurchaseForm,GenreForm,SignUpForm,SiteuserForm,AuthenticationFormWithoutPassword
from .models import Purchase,Genre,Siteuser,NameOnlyUser
from .graphs import make_pi
from django_pandas.io import read_frame
import os

from django.contrib.auth import login,logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

import locale
locale.setlocale(locale.LC_ALL, '')


# Create your views here.
@login_required
def index(request):
    user = request.user
    monthly_budget = user.siteuser.monthly_budget

    if not Genre.objects.bind_user(user):
        for default_genre in ['食費','交通費','交際費','被服費','雑貨費']:
            Genre.objects.create(author=user,genre_name=default_genre)
    genre_list = Genre.objects.bind_user(user)

    purchase_list = Purchase.objects.bind_user(user)
    purchase_form = PurchaseForm(label_suffix='')
    purchase_form.fields['genre'].queryset = genre_list
    genre_form = GenreForm(label_suffix='')
    site_user_form = SiteuserForm(instance=user.siteuser)

    this_month_purchase_list = purchase_list.thismonth()
    sum_price = sum([purchase.price for purchase in this_month_purchase_list])
    message = request.session.get('message','')


    params = {
    "purchase_list": purchase_list,
    "purchase_form": purchase_form,
    "genre_form": genre_form,
    "genre_list": genre_list,
    "this_month": timezone.now().strftime("%Y年%m月"),
    "this_month_purchase_list": this_month_purchase_list,
    "sum_price": sum_price,
    "message": message,
    "site_user_form": site_user_form,
    "rest_budget": monthly_budget - sum_price,
    }
    if this_month_purchase_list:
        this_month_purchase_df = read_frame(this_month_purchase_list)
        genre_proportion = this_month_purchase_df.groupby(by="genre").sum().sort_values("price",ascending=False)
        file_name = "graph" + user.username + ".jpg"
        params['graph'] = make_pi(genre_proportion["price"],file_name)

    return render(request,"webaccountbookapi/index.html",params)

@login_required
def update_budget(request):
    user = request.user
    if request.method == "POST":
        form = SiteuserForm(request.POST)
        if form.is_valid():
            monthly_budget = form.cleaned_data['monthly_budget']
        user.siteuser.monthly_budget = monthly_budget
        user.siteuser.save()
    return HttpResponseRedirect(reverse('webaccountbookapi:index'))


def add_purchase(request):
    user = request.user
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            genre = form.cleaned_data['genre']
            price = form.cleaned_data['price']
            purchase_date = form.cleaned_data['purchase_date']
            Purchase.objects.create(author=user,name=name,genre=genre,price=price,purchase_date=purchase_date)
            request.session['message'] = "家計簿に追加されました"
        else:
            request.session['message'] = "入力に不備があります"

    return HttpResponseRedirect(reverse('webaccountbookapi:index'))


def delete_purchase(request,purchase_id):
    del_purchse = get_object_or_404(Purchase,pk=purchase_id)
    request.session['message'] = f'{del_genre.name}を削除しました'
    del_purchse.delete()

    return HttpResponseRedirect(reverse('webaccountbookapi:index'))


def add_genre(request):
    user = request.user
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            genre_name= form.cleaned_data['genre_name']
            Genre.objects.create(author=user,genre_name=genre_name)
            request.session['message']="ジャンルが追加されました"
        else:
            request.session['message']="ジャンル名を記入してください"

    return HttpResponseRedirect(reverse('webaccountbookapi:index'))


def delete_genre(request,genre_id):
    del_genre = get_object_or_404(Genre,pk=genre_id)
    request.session['message'] = f'ジャンル  {del_genre.genre_name}  を削除しました'
    del_genre.delete()

    return HttpResponseRedirect(reverse('webaccountbookapi:index'))


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'webaccountbookapi/create.html'
    success_url = reverse_lazy('webaccountbookapi:index')

    def form_valid(self,form):
        user = form.save()
        login(self.request,user,backend='webaccountbookapi.backends.MyBackend')
        self.object = user
        return HttpResponseRedirect(self.get_success_url())


class login_to_index(LoginView):
    form_class = AuthenticationFormWithoutPassword
    template_name='webaccountbookapi/login.html'
    redirect_field_name = 'webaccountbookapi:index'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        login(self.request, NameOnlyUser.objects.get(username=username),backend='webaccountbookapi.backends.MyBackend')
        return HttpResponseRedirect(self.get_success_url())


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('webaccountbookapi:index'))

webaccountbookapi/templates/webaccountbookapi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'webaccountbookapi/index.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <footer>©taiyo narumi</footer>
  </body>
</html>

webaccountbookapi/templates/webaccountbookapi/create.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ウェブカケ　新規登録</title>
  </head>
  <body>
    {% if form.errors %}
    <p>すでにその名前で登録している人がいます</p>
    {% endif %}
    <form action="{% url 'webaccountbookapi:create' %}" method="post">
      {% csrf_token %}
      {{form.username}}
      <input type="submit" value='登録'>
  </body>
</html>

webaccountbookapi/templates/webaccountbookapi/genre.html
{% extends 'webaccountbookapi/base.html' %}

{% block title %}タイトル！{% endblock %}

{% block content %}
  <div class="register_genre">
    <form action="{% url 'webaccountbookapi:add_genre' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="登録">
    </form>
  </div>

  <div class="list">
      <ul>
      {% for genre in genre_list %}
        <li>
          {{genre.genre_name}}
          <a href="{% url 'webaccountbookapi:delete_genre' forloop.counter %}"><button>削除</button></a>
        </li>
      {% endfor %}
      </ul>
  </div>

{% endblock %}

webaccountbookapi/templates/webaccountbookapi/index.html
{% extends "webaccountbookapi/base.html" %}
{% load static %}

{% block title %}ウェブカケ{% endblock %}

{% block content %}
<header>
  <div id="rightparts">
    <p>ようこそ{{ user }}さん</p>
    <p><a href="{% url 'webaccountbookapi:logout' %}">ログアウト</a></p>
  </div>
  <a class="logo" href="{% url 'webaccountbookapi:index'  %}">いい感じのロゴ(固定しない)</a>
  <nav>
    <ul>
      <li>ナビ</li>
      <li>ゲー</li>
      <li>ション</li>
    </ul>
  </nav>
</header>

{% if message %}
<p class="message">{{ message }}</p>
{% endif %}
<div id="monthly_analyze">
  <h2><span class="under_line">{{ this_month }}<span class="small">の</span>家計</span></h2>
  {% if graph %}
    <img src="{{ graph.graph.url }}">
  {% else %}
    <p>まだ家計がありません</p>
  {% endif %}
  <div id="monthly_list">
    <table>
      <tr>
        <th>名前</th>
        <th>ジャンル</th>
        <th>価格</th>
        <th>購入日</th>
      </tr>
      {% for purchase in this_month_purchase_list %}
        <tr>
          <td>{{purchase.name}}</td>
          <td>{{purchase.genre}}</td>
          <td>{{purchase.price}}<span class="small">円</span></td>
          <td>{{purchase.purchase_date.month}} / {{purchase.purchase_date.day}}</td>
        </tr>
      {% endfor %}
    </table>
    <br>
    <table>
      <tr>
        <td><b>総計</b></td>
        <td><b>{{sum_price}}</b><span class="small">円</span></td>
      </tr>
      <tr>
        <td><b>今月残り</b></td>
        <td><b>{{rest_budget}}</b><span class="small">円</span></td>
      </tr>
    </table>

      <p class="sum_price"><span class="space"></span></p>
      <p><span class="space"></span></p>
      <form action="{% url 'webaccountbookapi:update_budget' %}" method="post">
        {% csrf_token %}
        {{site_user_form}}
        <input type="submit" value="更新">
      </form>
  </div>
</div>

<div class="register_purchase">
  <h2><span class="under_line">家計簿<span class="small">に</span>記入</span></h2>
  <form action="{% url 'webaccountbookapi:add_purchase' %}" method="post">
    {% csrf_token %}
    <div class="form_content">
      {% for field in purchase_form %}
        <div class="form_part">
          <p>{{ field.label_tag }}</p>
          {{ field }}
        </div>
      {% endfor %}
    </div>
    <input type="submit" value="登録" class="register_button">
  </form>
  <hr>
  <div class="recent_list">
    <h3>最近の入力</h3>
      <table>
        <tr>
          <th>名前</th>
          <th>ジャンル</th>
          <th>価格</th>
          <th>購入日</th>
        </tr>
        {% for purchase in purchase_list %}
          <tr>
            <th>{{purchase.name}}</th>
            <th>{{purchase.genre}}</th>
            <th>{{purchase.price}}</th>
            <th>{{purchase.purchase_date}}</th>
          </tr>
        {% endfor %}
      </table>
  </div>
</div>

<div class="register_genre">
  <h2><span class="under_line">ジャンル<span class="small">を</span>編集</span></h2>
  <form action="{% url 'webaccountbookapi:add_genre' %}" method="post">
    {% csrf_token %}
    <div class="form_content">
      {% for field in genre_form %}
        <div class="form_part">
          <p>{{ field.label_tag }}</p>
          {{ field }}
        </div>
      {% endfor %}
    </div>
    <input type="submit" value="登録" class="register_button">
  </form>
  <hr>

  <div class="list">
      <ul>
      {% for genre in genre_list %}
        <li>
          {{genre.genre_name}}
          <a href="{% url 'webaccountbookapi:delete_genre' genre.id %}"><button>削除</button></a>
        </li>
      {% endfor %}
      </ul>
  </div>
</div>

{% endblock %}

webaccountbookapi/templates/webaccountbookapi/login.html
{% extends 'webaccountbookapi/base.html' %}

{% block title %}ウェブカケログイン{% endblock %}

{% block content %}
<header>
  <a class="logo" href="{% url 'webaccountbookapi:index'  %}">いい感じのロゴ(固定しない)</a>
  <h1>いい感じのヒーロー画像</h1>
</header>

  {% if form.errors %}
  <p class="message">そのユーザ名は登録されていません。あたらしく始める場合は新規登録をクリックしてください。</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p class=message>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
    {% else %}
    <p class="message">Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <div>
    <form method="post" action="{% url 'webaccountbookapi:login' %}">
      {% csrf_token %}
      <div class="form_content">
        <p>{{ form.username.label_tag }}</p>
        <p>{{ form.username }}</p>
      </div>


      <input type="submit" value="login" class="register_button">
      <input type="hidden" name="next" value="{{ next }}">
    </form>
  </div>

  <p><a href={% url 'webaccountbookapi:create' %}>新規登録</a></p>
{% endblock %}